# Generated by Django 6.0.6 on 2026-06-22 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('label', models.CharField(blank=True, choices=[('diterima', 'Diterima'), ('tidak_diterima', 'Tidak Diterima')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('bobot', models.FloatField(blank=True, null=True)),
                ('jenis', models.CharField(choices=[('benefit', 'Benefit'), ('cost', 'Cost')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Kriteria',
            },
        ),
        migrations.CreateModel(
            name='HasilSeleksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai_utilitas', models.FloatField(blank=True, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('prediksi', models.CharField(blank=True, max_length=20, null=True)),
                ('probabilitas', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kandidat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rekrutmen_guru.kandidat')),
            ],
            options={
                'verbose_name_plural': 'Hasil Seleksi',
            },
        ),
        migrations.CreateModel(
            name='NilaiKriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nilai', models.FloatField()),
                ('kandidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nilai', to='rekrutmen_guru.kandidat')),
                ('kriteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rekrutmen_guru.kriteria')),
            ],
            options={
                'verbose_name_plural': 'Nilai Kriteria',
                'unique_together': {('kandidat', 'kriteria')},
            },
        ),
    ]
