# Generated by Django 6.0.6 on 2026-06-22 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutmen_guru', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidangStudi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Bidang Studi',
            },
        ),
        migrations.CreateModel(
            name='PeriodeRekrutmen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Periode Rekrutmen',
            },
        ),
        migrations.AddField(
            model_name='kandidat',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto_kandidat/'),
        ),
        migrations.AddField(
            model_name='kandidat',
            name='ipk',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kandidat',
            name='jenjang_pendidikan',
            field=models.CharField(blank=True, choices=[('D3', 'D3'), ('D4', 'D4'), ('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='kandidat',
            name='pengalaman_mengajar',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='kandidat',
            name='bidang_studi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rekrutmen_guru.bidangstudi'),
        ),
        migrations.AddField(
            model_name='kandidat',
            name='periode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rekrutmen_guru.perioderekrutmen'),
        ),
    ]
