# Generated by Django 6.0.6 on 2026-06-26 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutmen_guru', '0002_bidangstudi_perioderekrutmen_kandidat_foto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kandidat',
            name='status_tahap_1',
            field=models.CharField(choices=[('menunggu', 'Menunggu'), ('dipanggil', 'Dipanggil'), ('hadir', 'Hadir'), ('gugur', 'Gugur')], default='hadir', max_length=10, verbose_name='Status Kualifikasi Akademik'),
        ),
        migrations.AddField(
            model_name='kandidat',
            name='status_tahap_2',
            field=models.CharField(choices=[('menunggu', 'Menunggu'), ('dipanggil', 'Dipanggil'), ('hadir', 'Hadir'), ('gugur', 'Gugur')], default='menunggu', max_length=10, verbose_name='Status Psikotes & IQ'),
        ),
        migrations.AddField(
            model_name='kandidat',
            name='status_tahap_3',
            field=models.CharField(choices=[('menunggu', 'Menunggu'), ('dipanggil', 'Dipanggil'), ('hadir', 'Hadir'), ('gugur', 'Gugur')], default='menunggu', max_length=10, verbose_name='Status Wawancara & Ruhiyah'),
        ),
        migrations.AddField(
            model_name='kandidat',
            name='status_tahap_4',
            field=models.CharField(choices=[('menunggu', 'Menunggu'), ('dipanggil', 'Dipanggil'), ('hadir', 'Hadir'), ('gugur', 'Gugur')], default='menunggu', max_length=10, verbose_name='Status Micro Teaching'),
        ),
    ]
