# Generated by Django 6.0.6 on 2026-07-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutmen_guru', '0003_kandidat_status_tahap_1_kandidat_status_tahap_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kandidat',
            name='note_micro_teaching',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kandidat',
            name='note_wawancara',
            field=models.TextField(blank=True, null=True),
        ),
    ]
