# Generated by Django 6.0.6 on 2026-07-20 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutmen_guru', '0004_kandidat_note_micro_teaching_kandidat_note_wawancara'),
    ]

    operations = [
        migrations.AddField(
            model_name='kandidat',
            name='keputusan_akhir',
            field=models.CharField(blank=True, choices=[('diterima', 'Diterima'), ('tidak_diterima', 'Tidak Diterima')], max_length=20, null=True, verbose_name='Keputusan Akhir Yayasan'),
        ),
        migrations.AddField(
            model_name='kandidat',
            name='keputusan_tanggal',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
