# Generated by Django 6.0.6 on 2026-08-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutmen_guru', '0005_kandidat_keputusan_akhir_kandidat_keputusan_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilseleksi',
            name='ranking_xgboost',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
