# Generated by Django 6.0.6 on 2026-08-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rekrutmen_guru', '0006_hasilseleksi_ranking_xgboost'),
    ]

    operations = [
        migrations.AddField(
            model_name='hasilseleksi',
            name='probabilitas_layak',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
